import math
import random
n1=int(input("enter a value"))
n2=int(input("enter a value"))
print(n1,'+',n2,'=',n1+n2)
print(n1,'-',n2,'=',n1-n2)
print(n1,'*',n2,'=',n1*n2)
print(n1,'/',n2,'=',n1/n2)
print(n1,'%',n2,'=',n1%n2)
print(10,'^',n1,'=',pow(10,n1))
print(n1,'^',n2,'=',pow(n1,n2))
print(n1,'^',2,'=',pow(n1,2))
print(n1,'^',3,'=',pow(n1,3))
print('square root of',n1,'=',pow(n1,(1/2)))
print('cube root of',n1,'=',pow(n1,(1/3)))
print('sin(',n1,'degrees)=',math.sin(math.radians(n1)))
print('cos(',n1,'degrees)=',math.cos(math.radians(n1)))
print('tan(',n1,'degrees)=',math.tan(math.radians(n1)))
print('log(n1)',n1,'=',math.log(n1))
print('the log of 10',n1,'=',math.log10(n1))
print('the factorial of',n1,'=',math.factorial(n1))
print('the floor of',n1,'=',math.floor(n1))
print('the ceil of',n1,'=',math.ceil(n1))
print('the absolute value of',n1,'=',abs(n1))
print('the pi value is',math.pi)
print('the inverse of',n1,'=',(1/n1))
randomlist=random.sample(range(n1,n2),5)
print('the random numbers between',n1,'and',n2,'=',randomlist)
print('the exponent of',n1,'=',math.exp(n1))
print('the roundoff of',n1,'=',round(n1,n2))


